import { BaseModel } from '../base';
import ActiveUserMongoModel from './schema';

const errorCodes = {
    CREATE_DOC_ERROR: 'CREATE_ACTIVE_USER_ERROR',
    DOC_NOT_FOUND_ERROR: 'ACTIVE_USER_NOT_FOUND_ERROR',
    FIND_BY_ID_AND_UPDATE_DOC_ERROR: 'FIND_BY_ID_AND_UPDATE_ACTIVE_USER_ERROR',
    FIND_BY_ID_ERROR: 'FIND_ACTIVE_USER_BY_ID_ERROR',
    FIND_ONE_DOC_ERROR: 'FIND_ONE_ACTIVE_USER_ERROR',
    FIND_BY_QUERY_ERROR: 'FIND_ACTIVE_USER_BY_QUERY_ERROR',
    DUPLICATE_DOC_ERROR: 'DUPLICATE_ACTIVE_USER_ERROR',
    REMOVE_DOC_ERROR: 'REMOVE_ACTIVE_USER_DOC_ERROR',
    INSERT_MANY_DOC_ERROR: 'INSERT_MANY_ACTIVE_USER_DOC_ERROR',
    UPDATE_MANY_DOC_ERROR: 'UPDATE_MANY_ACTIVE_USER_DOC_ERROR'
};

export class ActiveUserModel extends BaseModel {
    constructor() {
        super(ActiveUserMongoModel, errorCodes);
    }
}
